---
common:

".gitlab-ci.yml":
  delete: true
appveyor.yml:
  delete: true
.gitpod.Dockerfile:
  unmanaged: true
.gitpod.yml:
  unmanaged: true
.github/workflows/nightly.yml:
  unmanaged: true
.github/workflows/pr_test.yml:
  unmanaged: true
.github/workflows/auto_release.yml:
  unmanaged: true
.github/workflows/spec.yml:
  checks: 'syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop'
  unmanaged: true
.github/workflows/release.yml:
  unmanaged: true
.travis.yml:
  delete: true
Gemfile:
  optional:
    ":development":
    - gem: github_changelog_generator
    - gem: puppet_litmus
      git: https://github.com/puppetlabs/puppet_litmus
      ref: main
      condition: Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.5.0')
Rakefile:
  changelog_user: "puppetlabs"

spec/spec_helper.rb:
  mock_with: ":rspec"
  coverage_report: true
spec/default_facts.yml:
  extra_facts:
    pe_server_version: 2018.1.0
    memory:
      "system":
        "total": "16.00 GiB"
        "total_bytes": 17179869184
    processors:
      "count": 8
spec/default_facts.yml:
  extra_facts:
    pe_postgresql_info:
      installed_server_version: 9.6
    pe_server_version: 2018.1.0
    memory:
      system:
        total: 16.00 GiB
        total_bytes: 17179869184
    processors:
      count: 8
